apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __APP_NAME__
spec:
  replicas: 2
  template:
    metadata:
      name: node-instance
      labels:
        app: __APP_NAME__
    spec:
      containers:
      - name: node-container
        image: __IMAGE__
        ports:
        - containerPort: 443
