apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-node
spec:
  replicas: 2
  selector:
    app: demo-node
  template:
    metadata:
      name: node-instance
      labels:
        app: demo-node
    spec:
      containers:
      - name: node-container
        image: gcr.io/haxweb-fr/demo-node
        ports:
        - containerPort: 443
