apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-node
spec:
  replicas: 2
  template:
    metadata:
      name: node-instance
      labels:
        app: demo-node
    spec:
      containers:
      - name: node-container
        image: gcr.io/haxweb-fr/demo-node
        ports:
        - containerPort: 443
